$schema: "http://json-schema.org/draft-07/schema#"
$id: "https://packetcoders.io/schemas/main"
type: "object"
properties:
  "private_asn": {"type": "integer", "format": "private-asn"}
required:
  - "private_asn"
  - "interfaces"
  - "syslog"
  - "dns_servers"
  - "ospf"
  - "bgp"
