$schema: http://json-schema.org/draft-07/schema#
type: object
properties:
  interfaces:
    type: array
    items:
      type: object
      properties:
        name:
          type: string
        ip:
          type: string
          format: ipv4
        netmask:
          type: string
          format: ipv4
      required:
        - name
        - ip
        - netmask
  syslog:
    type: array
    items:
      type: string
      format: ipv4
  dns_servers:
    type: array
    items:
      type: string
      format: ipv4
  ospf:
    type: object
    properties:
      area:
        type: integer
      networks:
        type: array
        items:
          type: string
          pattern: ^(?:(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)/[0-9]{1,2}$
    required:
      - area
      - networks
  bgp:
    type: object
    properties:
      local_as:
        type: integer
        minimum: 64512
        maximum: 65535
      neighbors:
        type: array
        items:
          type: object
          properties:
            ip:
              type: string
              format: ipv4
            remote_as:
              type: integer
              minimum: 64512
              maximum: 65535
          required:
            - ip
            - remote_as
    required:
      - local_as
      - neighbors
required:
  - interfaces
  - syslog
  - dns_servers
  - ospf
  - bgp
