name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["development"]
  workflow_dispatch:

jobs:
  lint:
    name: "Lint"
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync project dependencies
        run: uv pip install --system -r requirements.txt && uv sync --dev

      - name: Run Black
        run: black . --check

      - name: Run Autoflake
        run: autoflake -r . --expand-star-imports --remove-unused-variables --remove-all-unused-imports

      - name: Run Ruff Formatter Check
        run: ruff format . --check

      - name: Run Ruff Linter
        run: ruff check .

      - name: Run Mypy
        run: mypy .

  test:
    name: "Test"
    needs: lint
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Sync project dependencies
        run: uv sync --dev

      - name: Run Tests
        run: pytest tests -vvv --tb=short
