---
name: CI

on:
  push:
    branches: ["main"]
    paths:
      - "!**/README.md"
  pull_request:
    branches: ["development"]
    paths:
      - "!**/README.md"
  workflow_dispatch:

jobs:
  lint:
    name: "python-code-quality"
    strategy:
      matrix:
        python-version: [3.8.x]
        poetry-version: [1.3.1]
    runs-on: ubuntu-latest
    #defaults:
    #  run:
    #    working-directory: cyborg_web
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: ${{matrix.python-version}}
          poetry-version: ${{matrix.poetry-version}}

      - run: poetry run black . --check
      - run: poetry run autoflake -r . --expand-star-imports --remove-unused-variables --remove-all-unused-imports
      - run: poetry run ruff format . --check
      - run: poetry run ruff check .
      - run: poetry run mypy .

  test:
    name: "test"
    needs: "code-quality"
    strategy:
      matrix:
        python-version: [3.8.x]
        poetry-version: [1.3.1]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: "Setup Python, Poetry and Dependencies"
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: ${{matrix.python-version}}
          poetry-version: ${{matrix.poetry-version}}

      - name: Test
        run: poetry run pytest tests -vvv --tb=short
